import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetch(
    `https://aey7vvraaf.execute-api.us-east-1.amazonaws.com/dev/v2/schools/teresiano?registered_student=true`,
    { next: { revalidate: 86400 } }
  )
  const schoolData = await data.json()
  console.log('SCHOOL DATA', schoolData)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1>PRIMEIRO LAYOUT</h1>
        {children}
      </body>
    </html>
  );
}
